name: GithubActions Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit Test
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          cd GithubActionsDemo
          xcodebuild clean test -project GithubActionsDemo
.xcodeproj -scheme GithubActionsDemo -destination 'platform=iOS Simulator,OS=13.3,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
