name: GithubActions Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  

jobs:
  test:
    name: Unit Test
    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11', 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (3rd generation)']
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild clean test -project GithubActionsDemo.xcodeproj -scheme GithubActionsDemo -destination "${{ matrix.destination }}"
  
  build:
    name: Build Archive
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild archive -project GithubActionsDemo.xcodeproj -scheme GithubActionsDemo -sdk iphoneos -configuration Debug -archivePath $PWD/build/GithubActionsDemo.xcarchive -allowProvisioningUpdates"
  
